remote_theme: jekyll/minima
title: tijsboussier.eu
name: "Tijs Boussier"
description: "I'm Tijs. This website is my playground, to mess around with writing and web design. For right now, though, it really is just a dime-in-a-dozen blog."
header_pages:
  - about.md
minima:
  social_links:
    - { platform: bluesky, user_url: "https://bsky.app/profile/tijsboussier.eu" }
    - { platform: instagram, user_url: "https://www.instagram.com/mrhappyboots" }
  date_format: "%d %B %Y"
plugins:
  - jekyll-feed
